// Code generated by qtc from "404.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/404.qtpl:1
package templates

//line templates/404.qtpl:1
import "github.com/painhardcore/Gobrou/models"

//line templates/404.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/404.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/404.qtpl:5
type NotFoundPage struct {
	Cfg   *models.Config
	Posts []models.Post
}

//line templates/404.qtpl:12
func (p *NotFoundPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/404.qtpl:12
	qw422016.N().S(`
404 - Page Not Found - `)
//line templates/404.qtpl:13
	qw422016.E().S(p.Cfg.Title)
//line templates/404.qtpl:13
	qw422016.N().S(`
`)
//line templates/404.qtpl:14
}

//line templates/404.qtpl:14
func (p *NotFoundPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/404.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/404.qtpl:14
	p.StreamTitle(qw422016)
//line templates/404.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line templates/404.qtpl:14
}

//line templates/404.qtpl:14
func (p *NotFoundPage) Title() string {
//line templates/404.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/404.qtpl:14
	p.WriteTitle(qb422016)
//line templates/404.qtpl:14
	qs422016 := string(qb422016.B)
//line templates/404.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/404.qtpl:14
	return qs422016
//line templates/404.qtpl:14
}

//line templates/404.qtpl:16
func (p *NotFoundPage) StreamStyle(qw422016 *qt422016.Writer) {
//line templates/404.qtpl:16
	qw422016.N().S(`
.not-found-container {
    text-align: center;
    margin-top: 60px;
}
.not-found-title {
    font-size: 4em;
    margin: 0;
    color: #666;
}
.not-found-subtitle {
    font-size: 1.2em;
    color: #888;
    margin: 20px 0;
}
.recent-posts {
    margin-top: 40px;
    text-align: left;
}
.recent-posts h3 {
    text-align: center;
    margin-bottom: 20px;
}
.recent-posts ul {
    list-style: none;
    padding: 0;
}
.recent-posts li {
    margin: 10px 0;
    padding: 10px;
    background: #f5f5f5;
    border-radius: 4px;
}
.recent-posts a {
    text-decoration: none;
    color: #333;
    font-weight: 500;
}
.recent-posts a:hover {
    text-decoration: underline;
}

@media (prefers-color-scheme: dark) {
    .not-found-title {
        color: #888;
    }
    .not-found-subtitle {
        color: #666;
    }
    .recent-posts li {
        background: #161b22;
    }
    .recent-posts a {
        color: #c9d1d9;
    }
}

`)
//line templates/404.qtpl:73
}

//line templates/404.qtpl:73
func (p *NotFoundPage) WriteStyle(qq422016 qtio422016.Writer) {
//line templates/404.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/404.qtpl:73
	p.StreamStyle(qw422016)
//line templates/404.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line templates/404.qtpl:73
}

//line templates/404.qtpl:73
func (p *NotFoundPage) Style() string {
//line templates/404.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/404.qtpl:73
	p.WriteStyle(qb422016)
//line templates/404.qtpl:73
	qs422016 := string(qb422016.B)
//line templates/404.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/404.qtpl:73
	return qs422016
//line templates/404.qtpl:73
}

//line templates/404.qtpl:75
func (p *NotFoundPage) StreamHead(qw422016 *qt422016.Writer) {
//line templates/404.qtpl:75
	qw422016.N().S(`
`)
//line templates/404.qtpl:76
}

//line templates/404.qtpl:76
func (p *NotFoundPage) WriteHead(qq422016 qtio422016.Writer) {
//line templates/404.qtpl:76
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/404.qtpl:76
	p.StreamHead(qw422016)
//line templates/404.qtpl:76
	qt422016.ReleaseWriter(qw422016)
//line templates/404.qtpl:76
}

//line templates/404.qtpl:76
func (p *NotFoundPage) Head() string {
//line templates/404.qtpl:76
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/404.qtpl:76
	p.WriteHead(qb422016)
//line templates/404.qtpl:76
	qs422016 := string(qb422016.B)
//line templates/404.qtpl:76
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/404.qtpl:76
	return qs422016
//line templates/404.qtpl:76
}

//line templates/404.qtpl:78
func (p *NotFoundPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/404.qtpl:78
	qw422016.N().S(`
<div class="not-found-container">
    <h1 class="not-found-title">404</h1>
    <h2 class="not-found-subtitle">Oops! This page seems to have wandered off.</h2>
    <p>Don't worry, even the best explorers sometimes take a wrong turn. Here are some posts you might find interesting:</p>
    
    <div class="recent-posts">
        <h3>Recent Posts</h3>
        <ul>
            `)
//line templates/404.qtpl:87
	for _, post := range p.Posts {
//line templates/404.qtpl:87
		qw422016.N().S(`
            <li><a href="/posts/`)
//line templates/404.qtpl:88
		qw422016.E().S(post.Slug)
//line templates/404.qtpl:88
		qw422016.N().S(`/">`)
//line templates/404.qtpl:88
		qw422016.E().S(post.Title)
//line templates/404.qtpl:88
		qw422016.N().S(`</a></li>
            `)
//line templates/404.qtpl:89
	}
//line templates/404.qtpl:89
	qw422016.N().S(`
        </ul>
    </div>
    
    <p style="margin-top: 40px;">
        <a href="/" style="color: #007bff; text-decoration: none; font-weight: 500;">← Back to Home</a>
    </p>
</div>
`)
//line templates/404.qtpl:97
}

//line templates/404.qtpl:97
func (p *NotFoundPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/404.qtpl:97
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/404.qtpl:97
	p.StreamBody(qw422016)
//line templates/404.qtpl:97
	qt422016.ReleaseWriter(qw422016)
//line templates/404.qtpl:97
}

//line templates/404.qtpl:97
func (p *NotFoundPage) Body() string {
//line templates/404.qtpl:97
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/404.qtpl:97
	p.WriteBody(qb422016)
//line templates/404.qtpl:97
	qs422016 := string(qb422016.B)
//line templates/404.qtpl:97
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/404.qtpl:97
	return qs422016
//line templates/404.qtpl:97
}
