// Code generated by qtc from "post.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/post.qtpl:1
package templates

//line templates/post.qtpl:1
import "github.com/painhardcore/Gobrou/models"

//line templates/post.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/post.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/post.qtpl:5
type PostPage struct {
	Post *models.Post
}

//line templates/post.qtpl:11
func (p *PostPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:11
	qw422016.N().S(`
`)
//line templates/post.qtpl:12
	qw422016.E().S(p.Post.Title)
//line templates/post.qtpl:12
	qw422016.N().S(`
`)
//line templates/post.qtpl:13
}

//line templates/post.qtpl:13
func (p *PostPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:13
	p.StreamTitle(qw422016)
//line templates/post.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:13
}

//line templates/post.qtpl:13
func (p *PostPage) Title() string {
//line templates/post.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:13
	p.WriteTitle(qb422016)
//line templates/post.qtpl:13
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:13
	return qs422016
//line templates/post.qtpl:13
}

//line templates/post.qtpl:15
func (p *PostPage) StreamStyle(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:15
	qw422016.N().S(`
.post-meta {
            color: #888;
            font-size: 0.9em;
}
.back-link {
            display: block;
            margin-top: 20px;
            color: #0000EE;
            text-decoration: none;
}
.back-link:hover {
            text-decoration: underline;
}

`)
//line templates/post.qtpl:30
	qw422016.N().S(p.Post.CSS)
//line templates/post.qtpl:30
	qw422016.N().S(`
`)
//line templates/post.qtpl:31
}

//line templates/post.qtpl:31
func (p *PostPage) WriteStyle(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:31
	p.StreamStyle(qw422016)
//line templates/post.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:31
}

//line templates/post.qtpl:31
func (p *PostPage) Style() string {
//line templates/post.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:31
	p.WriteStyle(qb422016)
//line templates/post.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:31
	return qs422016
//line templates/post.qtpl:31
}

//line templates/post.qtpl:33
func (p *PostPage) StreamHead(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:33
	qw422016.N().S(`
`)
//line templates/post.qtpl:34
}

//line templates/post.qtpl:34
func (p *PostPage) WriteHead(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:34
	p.StreamHead(qw422016)
//line templates/post.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:34
}

//line templates/post.qtpl:34
func (p *PostPage) Head() string {
//line templates/post.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:34
	p.WriteHead(qb422016)
//line templates/post.qtpl:34
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:34
	return qs422016
//line templates/post.qtpl:34
}

//line templates/post.qtpl:36
func (p *PostPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:36
	qw422016.N().S(`
<a href="javascript:history.back()" class="back-link">Go Back</a>
    <header>
        <h1>`)
//line templates/post.qtpl:39
	qw422016.E().S(p.Post.Title)
//line templates/post.qtpl:39
	qw422016.N().S(`</h1>
        <p class="Post-meta">`)
//line templates/post.qtpl:40
	qw422016.E().S(p.Post.Date.Format("January 2, 2006 | at 3:04 PM"))
//line templates/post.qtpl:40
	qw422016.N().S(`</p>
    </header>
    <main>
        `)
//line templates/post.qtpl:43
	qw422016.N().S(p.Post.Content)
//line templates/post.qtpl:43
	qw422016.N().S(` 
    </main>
`)
//line templates/post.qtpl:45
}

//line templates/post.qtpl:45
func (p *PostPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:45
	p.StreamBody(qw422016)
//line templates/post.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:45
}

//line templates/post.qtpl:45
func (p *PostPage) Body() string {
//line templates/post.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:45
	p.WriteBody(qb422016)
//line templates/post.qtpl:45
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:45
	return qs422016
//line templates/post.qtpl:45
}
