name: Build and Release

on:
  push:
    branches:
      - master 
  create:
    tags:
      - '*'
permissions:
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build the tool
      run: go build -o gobrou

    - name: Archive the build
      uses: actions/upload-artifact@v4
      with:
        name: gobrou
        path: gobrou

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download the build
      uses: actions/download-artifact@v4
      with:
        name: gobrou

    - name: Create or update release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload asset with GH CLI (overwrite / replace)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # GITHUB_REF_NAME and GITHUB_REPOSITORY are provided by Actions
        echo "Uploading gobrou to release ${GITHUB_REF_NAME} (repo: ${GITHUB_REPOSITORY})"
        gh release upload "${GITHUB_REF_NAME}" gobrou --clobber --repo "${GITHUB_REPOSITORY}"
